spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.66.102:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml