server:
  port: 9001

spring:
  application:
    name: nacos-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.111:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'